[default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 200
remappings = ['ds-test/=lib/ds-test/src/']
fuzz_runs = 1000

# See more config options https://github.com/gakonst/foundry/tree/master/config